services:

  node:
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
    healthcheck:
      test: curl --fail http://localhost:3001 || exit 1
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-express:
    image: mongo-express:1.0.0-alpha
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_EXPRESS_USER
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_EXPRESS_PASSWORD
    ports:
      - "127.0.0.1:8081:8081" # Prevents exposure beyond localhost
    depends_on: 
      - mongo

volumes:
   mongodb:
   mongodb_config: